version: '2'
services:
    nginx:
        image: "${DOCKER_USER}/nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - web
    web:
        image: "${DOCKER_USER}/web:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.python
        networks:
            - frontend
            - backend
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
            MYSQL_PORT: ${MYSQL_PORT}

        depends_on:
            - mysql
        links:
            - mysql
            - redis     
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ: ${TZ}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
            MYSQL_PORT: ${MYSQL_PORT}
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
        depends_on:
            - redis             
    redis: 
        image: "${DOCKER_USER}/redis:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        depends_on:
            - redis1          
        networks:
            - backend   
    redis1: 
        image: "${DOCKER_USER}/redis1:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - "6380"          
        networks:
            - backend   
        depends_on:
            - redis2             
    redis2: 
        image: "${DOCKER_USER}/redis2:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - "6381"          
        networks:
            - backend
        depends_on:
            - redis3           
    redis3: 
        image: "${DOCKER_USER}/redis3:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - "6382"          
        networks:
            - backend 
                       
volumes:
    mysql-data:

networks:
    frontend:
    backend:
