version: '2'
services:
    nginx:
        image: "${DOCKER_USER}/lnmp-nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - web
    web:
        image: "${DOCKER_USER}/lnmp-web:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.python
        networks:
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD: Passw0rd            
        depends_on:
            - mysql
        links:
            - mysql    
    mysql:
        image: mysql:5.7
        volumes:
            - ~/data/mysql-data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: Passw0rd
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
