
FROM python:3.5

RUN mkdir -p /code
WORKDIR /code

COPY requirements.txt /code
RUN pip install --no-cache-dir -r requirements.txt

COPY ./site /code
CMD ["/code/uwsgi/init.sh"]


ENV MYSQL_USER admin
ENV MYSQL_DATABASE test
ENV MYSQL_ROOT_PASSWORD admin
ENV MYSQL_PASSWORD password
ENV MYSQL_CONTAINER_NAME mysql
ENV MYSQL_PORT 3306