
FROM python:3.5

RUN mkdir -p /code
WORKDIR /code

COPY requirements.txt /code
RUN pip install --no-cache-dir -r /code/requirements.txt

COPY ./site /code
COPY ./uwsgi /code
CMD ["/code/init.sh"]


ENV MYSQL_USER admin
ENV MYSQL_DATABASE test
ENV MYSQL_ROOT_PASSWORD p123456
ENV MYSQL_PASSWORD p123456
ENV MYSQL_CONTAINER_NAME mysql
ENV MYSQL_PORT 3306

