version: '2'
services:
    redis1: 
        image: "${DOCKER_USER}/redis1:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - "6380"          
        networks:
            - backend   
            
    redis2: 
        image: "${DOCKER_USER}/redis2:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - "6381"          
        networks:
            - backend
        depends_on:
            - redis1            
    redis3: 
        image: "${DOCKER_USER}/redis3:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - "6382"          
        networks:
            - backend 
        depends_on:
            - redis2                                            
volumes:
    mysql-data:

networks:
    frontend:
    backend:
