version: '2'
services:
    nginx:
        image: "${DOCKER_USER}/lnmp-nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - python
    python:
        image: "${DOCKER_USER}/lnmp-python:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.python
        environment:
            MYSQL_PASSWORD: p123456
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ:'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: p123456
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
